# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 16:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_username', message=b'Username must be alphanumeric or contain ".@+-"', regex=b'^[a-zA-Z0-9.@+-]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
